### ISSUE TITLE
 error when try to install layer in AWS CodeBuild pipeline

### ISSUE THREAD

**Issue by ysolis** [newrelic/newrelic-lambda-cli#185]
## Description
If i try to install the layer in a AWS CodeBuild pipeline, an obscure error appears.

## Steps to Reproduce
add the instructions to install the layer in the AWS buildspec.yml

```
####################################
version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
    - apt update -y
    - apt install nodejs -y
    - npm install -g serverless
    - npm install
    - pip3 install --upgrade newrelic-lambda-cli
  build:
    commands:
    - sls deploy --stage $stage --region $region -v
  post_build:
    commands:
    - newrelic-lambda layers install --function all --nr-account-id XXXXXXX --nr-api-key NRAK-XXXXXXXXXXXXXXXXXXX --upgrade --aws-region $region

```

## Expected Behaviour
Install the new layer in the ```post_build``` process (after build/install)

## Relevant Logs / Console output
liens from AWS CodeBuild logs
```
[Container] 2021/11/21 01:25:05 Running command pip3 install --upgrade newrelic-lambda-cli
Collecting newrelic-lambda-cli
  Downloading newrelic-lambda-cli-0.6.5.tar.gz (39 kB)
  ...
  ...
  Successfully installed blessings-1.7 curtsies-0.3.10 cwcwidth-0.1.5 emoji-1.6.1 enquiries-0.1.0 gql-2.0.0 graphql-core-2.3.2 newrelic-lambda-cli-0.6.5 promise-2.3 rx-1.6.1 tabulate-0.8.9
  ...
  ...
<span><span>

[Container] 2021/11/21 01:27:28 Entering phase POST_BUILD
[Container] 2021/11/21 01:27:28 Running command newrelic-lambda layers install --function all --nr-account-id XXXXXXX --nr-api-key NRAK-XXXXXXXXXXXXXXXXXXXXXXXX --upgrade --aws-region $region
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.10/bin/newrelic-lambda", line 8, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/newrelic_lambda_cli/cli/__init__.py", line 25, in main
    cli()
...
...
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/blessings/__init__.py", line 97, in __init__
    setupterm(kind or environ.get('TERM', 'unknown'),
_curses.error: setupterm: could not find terminal
[Container] 2021/11/21 01:27:32 Command did not exit successfully newrelic-lambda layers install --function all --nr-account-id XXXXXXXX --nr-api-key NRAK-XXXXXXXXXXXXXXXXXXXXXXXXXXXX --upgrade --aws-region $region exit status 1
[Container] 2021/11/21 01:27:32 Phase complete: POST_BUILD State: FAILED
[Container] 2021/11/21 01:27:32 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: newrelic-lambda layers install --function all --nr-account-id XXXXXXXX --nr-api-key NRAK-XXXXXXXXXXXXXXXXXXXXXXXXXXX --upgrade --aws-region $region. Reason: exit status 1
```

## Your Environment
AWS CodeCommit repository
AWS CodeBuild process
